# Define display_board that accepts a board and prints
# out the current state.
board = [" "," "," "," "," "," "," "," "," "]
def display_board(board)
  puts " O |   |   "
  puts "-----------"
  puts "   | X |   "
  puts "-----------"
  puts "   |   |   "
  puts " X | X | X "
  puts "-----------"
  puts "   |   |   "
  puts "-----------"
  puts " O | O | O "
  puts " X |   |   "
  puts "-----------"
  puts "   | X |   "
  puts "-----------"
  puts "   |   | X "
  puts "   |   | O  "
  puts "-----------"
  puts "   | O |   "
  puts "-----------"
  puts " O |   |   "
  puts " X | X | X "
  puts "-----------"
  puts " X| O | O "
  puts "-----------"
  puts " X | O | O "
  puts " X | O | X "
  puts "-----------"
  puts " O | X | X "
  puts "-----------"
  puts " O | X | O  "
end
