def display_board(board)
  board = [" ", " ", " ", " ", " ", " ", " ", " ", " "]
    print "   "
    print "|"
    print "   "
    print "|"
    puts "   "
    puts "-----------"
    print "   "
    print "|"
    print "   "
    print "|"
    puts "   "
    puts "-----------"
    print "   "
    print "|"
    print "   "
    print "|"
    puts "   "
  board = [" ", " ", " ", " ", " X ", " ", " ", " ", " "]
    print "   "
    print "|"
    print "   "
    print "|"
    puts "   "
    puts "-----------"
    print "   "
    print "|"
    print " X "
    print "|"
    puts "   "
    puts "-----------"
    print "   "
    print "|"
    print "   "
    print "|"
    puts "   "
board = [" O ", " ", " ", " ", " ", " ", " ", " ", " "]
    print " O "
    print "|"
    print "   "
    print "|"
    puts "   "
    puts "-----------"
    print "   "
    print "|"
    print "  "
    print "|"
    puts "   "
    puts "-----------"
    print "   "
    print "|"
    print "   "
    print "|"
    puts "   "
  board = [" X ", " X ", " X ", " ", " ", " ", " ", " ", " "]
    print " X "
    print "|"
    print " X "
    print "|"
    puts " X "
    puts "-----------"
    print "   "
    print "|"
    print "  "
    print "|"
    puts "   "
    puts "-----------"
    print "   "
    print "|"
    print "   "
    print "|"
    puts "   "
   board = [" ", " ", " ", " ", " ", " ", " O ", " O ", " O "]
    print "   "
    print "|"
    print "   "
    print "|"
    puts "   "
    puts "-----------"
    print "   "
    print "|"
    print "  "
    print "|"
    puts "   "
    puts "-----------"
    print " O "
    print "|"
    print " O "
    print "|"
    puts " O "
  board = [" X ", " ", " ", " ", " X ", " ", " ", " ", " X "]
    print " X "
    print "|"
    print "   "
    print "|"
    puts "   "
    puts "-----------"
    print "   "
    print "|"
    print " X "
    print "|"
    puts "   "
    puts "-----------"
    print "   "
    print "|"
    print "   "
    print "|"
    puts " X "
  board = [" ", " ", " O ", " ", " O ", " ", " O ", " ", " "]
    print "   "
    print "|"
    print "   "
    print "|"
    puts " O  "
    puts "-----------"
    print "   "
    print "|"
    print " O "
    print "|"
    puts "   "
    puts "-----------"
    print " O "
    print "|"
    print "   "
    print "|"
    puts "   "#
  board = ["X", "X", "X", "X", "O", "O", "X", "O", "O"]
    print " X "
    print "|"
    print " X "
    print "|"
    puts " X "
    puts "-----------"
    print " X "
    print "|"
    print " O "
    print "|"
    puts " O "
    puts "-----------"
    print " X "
    print "|"
    print " O "
    print "|"
    puts " O "
  board = ["X", "O", "X", "O", "X", "X", "O", "X", "O"]
    print " X "
    print "|"
    print " O "
    print "|"
    puts " X "
    puts "-----------"
    print " O "
    print "|"
    print " X "
    print "|"
    puts " X "
    puts "-----------"
    print " O "
    print "|"
    print " X "
    print "|"
    puts " O "

  board = ["X", "X", "X", "X", "X", "X", "X", "X", "X"]
    print " X "
    print "|"
    print " X "
    print "|"
    puts " X "
    puts "-----------"
    print " X "
    print "|"
    print " X "
    print "|"
    puts " X "
    puts "-----------"
    print " X "
    print "|"
    print " X "
    print "|"
    puts " X "
  board = ["O", "O", "O", "O", "O", "O", "O", "O", "O"]
    print " O "
    print "|"
    print " O "
    print "|"
    puts " O "
    puts "-----------"
    print " O "
    print "|"
    print " O "
    print "|"
    puts " O "
    puts "-----------"
    print " O "
    print "|"
    print " O "
    print "|"
    puts " O "
end