# Define display_board that accepts a board and prints
# out the current state.
def display_board(board = [" "," "," "," "," "," "," "," "," "])
  puts "   |   |   "
  puts "-----------"
  puts "   |   |   "
  puts "-----------"
  puts "   |   |   "

  board[4] = "X"
  puts "   |   |   "
  puts "-----------"
  puts "   | X |   "
  puts "-----------"
  puts "   |   |   "
  
  board[0] = "O"
  puts " O |   |   "
  puts "-----------"
  puts "   |   |   "
  puts "-----------"
  puts "   |   |   "

  board[0] = "O"
  board[4] = "X"
  puts " O |   |   "
  puts "-----------"
  puts "   | X |   "
  puts "-----------"
  puts "   |   |   "

  board[0] = "X"
  board[1] = "X"
  board[2] = "X"
  puts " X | X | X "
  puts "-----------"
  puts "   |   |   "
  puts "-----------"
  puts "   |   |   "

  board = [" "," "," "," "," "," ","O","O","O"]
  board[6] = "O"
  board[7] = "O"
  board[8] = "O"
  puts "   |   |   "
  puts "-----------"
  puts "   |   |   "
  puts "-----------"
  puts " O | O | O "

  board[0] = "X"
  board[4] = "X"
  board[8] = "X"
  puts " X |   |   "
  puts "-----------"
  puts "   | X |   "
  puts "-----------"
  puts "   |   | X "

  board[2] = "O"
  board[4] = "O"
  board[6] = "O"
  puts "   |   | O "
  puts "-----------"
  puts "   | O |   "
  puts "-----------"
  puts " O |   |   "

  board = ["X","X","X","X","O","O","X","O","O"]
  puts " X | X | X "
  puts "-----------"
  puts " X | O | O "
  puts "-----------"
  puts " X | O | O "

  board = ["X", "O", "X", "O", "X", "X", "O", "X", "O"]
  puts " X | O | X "
  puts "-----------"
  puts " O | X | X "
  puts "-----------"
  puts " O | X | O "

  board = ["X", "X", "X", "X", "X", "X", "X", "X", "X"]
  board[0] = "X"
  board[1] = "X"
  board[2] = "X"
  board[3] = "X"
  board[4] = "X"
  board[5] = "X"
  board[6] = "X"
  board[7] = "X"
  board[8] = "X"
  puts " X | X | X "
  puts "-----------"
  puts " X | X | X "
  puts "-----------"
  puts " X | X | X "

  board = ["O", "O", "O", "O", "O", "O", "O", "O", "O"]
  board[0] = "O"
  board[1] = "O"
  board[2] = "O"
  board[3] = "O"
  board[4] = "O"
  board[5] = "O"
  board[6] = "O"
  board[7] = "O"
  board[8] = "O"
  puts " O | O | O "
  puts "-----------"
  puts " O | O | O "
  puts "-----------"
  puts " O | O | O "
end
